# hardware-configuration.nix: Generated by nixos-generate-config; edit for encryption/subvolumes.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];  # AMD Ryzen hardware.
  boot.initrd.kernelModules = [ "amdgpu" ];  # Integrated graphics.
  boot.kernelModules = [ "kvm-amd" ];  # Virtualization.
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/enc";  # LUKS unlocked device.
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd:3" "noatime" "ssd" "space_cache=v2" ];  # Optimized for SSD/battery.
  };

  fileSystems."/home" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd:3" "noatime" "ssd" "space_cache=v2" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd:3" "noatime" "ssd" "space_cache=v2" "nodatacow" ];  # No CoW for /nix to speed builds.
  };

  fileSystems."/boot" = {
    device = "/dev/nvme0n1p1";  # EFI partition (FAT32, 1GB).
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/mapper/swap"; } ];  # Encrypted swap for hibernation (~34GB).

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
